model:
  name: mobilenet_v1
  framework: tensorflow
  inputs: []
  outputs: []
device: cpu
evaluation:
  accuracy:
    metric:
      topk: 1
    dataloader:
      batch_size: 32
      dataset:
        ImageRecord:
          root: small_dataset
      transform:
        ParseDecodeImagenet: {}
        BilinearImagenet:
          height: 224
          width: 224
      last_batch: rollover
  performance:
    configs:
      cores_per_instance: 4
      num_of_instance: 7
    dataloader:
      batch_size: 1
      last_batch: discard
      dataset:
        ImageRecord:
          root: small_dataset
      transform:
        ParseDecodeImagenet: {}
        ResizeCropImagenet:
          height: 224
          width: 224
          mean_value:
          - 123.68
          - 116.78
          - 103.94
    warmup: 5
    iteration: -1
